In [75]:
import numpy as np

In [76]:
np.set_printoptions(precision=2)

In [77]:
#Write a NumPy program to create an array of 10 zeros
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [78]:
#Write a NumPy program to create an array of 10 ones.
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [79]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.
a=np.arange(0,9)
print(a)
a.reshape(3,3)


[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
#Write a NumPy program to reverse an array (first element becomes the last).
b=np.arange(0,10,2)
print(b)
rev_arr=np.flipud(b)
print(rev_arr)

[0 2 4 6 8]
[8 6 4 2 0]


In [81]:
#Write a NumPy program to extract all odd numbers from an array.
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
b=a[a%2==1]
print(b)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  3  5  7  9 11]


In [82]:
#Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.
a=np.arange(1,10)
print(a)
b=a.reshape(3,3)
print(b)
print(np.sum(b))
print(np.sum(b, axis=0))
print("Sum of each row:")
print(np.sum(b, axis=1))
print(np.mean(b))
print(np.std(b))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
Sum of each row:
[ 6 15 24]
5.0
2.581988897471611


In [83]:
#Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.
c=np.random.randint(1,50,25)
print(c)
b=c.reshape(5,5)
print(b)
n=np.min(b)
print(n)
m=np.max(b)
print(m)


[10 49 17 30 27 11 44 11 13  5 21 31 35 21  8 35  4 26 26 34  8 40 23 13
 44]
[[10 49 17 30 27]
 [11 44 11 13  5]
 [21 31 35 21  8]
 [35  4 26 26 34]
 [ 8 40 23 13 44]]
4
49


In [84]:
#Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [85]:
#Write a NumPy program to multiply two given matrices.
a=np.random.randint(1,20,9)
print(a)
b=a.reshape(3,3)
print(b)
c=np.arange(1,10)
print(c)
d=c.reshape(3,3)
print(d)

f=b*d

print(f)



[12  7  4  1  4  1  5  5  9]
[[12  7  4]
 [ 1  4  1]
 [ 5  5  9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[12 14 12]
 [ 4 20  6]
 [35 40 81]]


In [86]:
#Write a NumPy program to find the unique elements of an array.
n1=np.random.randint(1,20,10)
print(n1)
n2=np.random.randint(1,20,10)
print(n2)
n3=np.setdiff1d(n2,n1)
print(n3)

[ 5  2 10  9  4 11 17  9  1 18]
[16  9 19  4  6  4 14  4 10  9]
[ 6 14 16 19]


In [87]:
#Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.
a=np.arange(1,10)
print(a)
b=a.reshape(3,3)
print(b)
c=b[b%2==1]
print(c)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 3 5 7 9]


In [88]:
#Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.
a=np.arange(1,10)
print(a)
b=a.reshape(3,3)
print(b)
c=b[b%2==0]
print(c)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 4 6 8]


In [89]:
#Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive).
a=np.random.randint(1,20,(4,4))
print(a)
print("the first 3 rows are:",a[:1,:3])
print('the columns from index 1 to 4:',a[:,:1])


[[10  3  2  6]
 [ 6 12  7 11]
 [ 4 19  1 11]
 [ 2 12 13  6]]
the first 3 rows are: [[10  3  2]]
the columns from index 1 to 4: [[10]
 [ 6]
 [ 4]
 [ 2]]


In [90]:
#Write a NumPy program to reverse the order of elements in each column of a 2D array.
a=np.random.randint(1,20,(4,4))
print(a)

b = np.flipud (a)
print(b)

[[14  4 10  8]
 [ 1  4 16  6]
 [ 9 16  8  2]
 [ 6  9 11 16]]
[[ 6  9 11 16]
 [ 9 16  8  2]
 [ 1  4 16  6]
 [14  4 10  8]]


In [91]:
#Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared.

a=np.random.randint(1,20,(4,4))
print(a)
x=0
b=np.fill_diagonal(a,x)
print(b)

[[ 6 15  5  6]
 [ 4 18 16 14]
 [11  4  9 18]
 [ 9  7  3 16]]
None
